pipeline {
    agent {
    tools {
        maven 'maven'
    }
    stages {
        stage('checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/chaithra0317/simple-java-maven-app.git'
            }
        }
        stage('build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('sonar analysis') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
